# Generated by Django 2.1.3 on 2022-07-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_with',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
